language: ruby
rvm:
  - 2.4.0
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c "create database community_share_test;" -U postgres
bundler_args: --without production
script:
 - bundle exec rspec
 - bundle exec rubocop
