default: &default
  adapter: postgresql
  host: 127.0.0.1
  database: <%= ENV["POSTGRESQL_DATABASE"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  username: <%= ENV["POSTGRESQL_USERNAME"] %>
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["POSTGRESQL_DATABASE"] %>_test

production:
  <<: *default
